<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.4</version>
    </parent>
    <groupId>com.loserico</groupId>
    <artifactId>loser-starter</artifactId>
    <packaging>pom</packaging>
    <version>17.0.2</version>
    <name>Loser Spring Starter Parent</name>

    <properties>
        <java.version>17</java.version>
        <loser.version>17.0.2</loser.version>
        <sentinel.version>1.8.6</sentinel.version>
        <!--<gateway.version>4.1.2</gateway.version>-->
        <gateway.version>2.2.10.RELEASE</gateway.version>
    </properties>

    <modules>
        <module>loser-spring-boot-starter</module>
        <module>loser-spring-boot</module>
        <module>loser-spring-boot-web-starter</module>
        <module>loser-cloud-gateway-starter</module>
        <module>loser-cloud-gateway</module>
        <module>loser-spring-boot-security</module>
        <module>loser-spring-boot-security-starter</module>
        <module>loser-spring-boot-webflux</module>
        <module>loser-spring-boot-es-starter</module>
        <module>loser-spring-boot-oauth2</module>
        <module>loser-spring-boot-oauth2-starter</module>
        <module>loser-spring-cloud</module>
        <module>loser-spring-cloud-starter</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2023.0.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.security.oauth</groupId>
                <artifactId>spring-security-oauth2</artifactId>
                <version>2.5.2.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2023.0.1.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>1.18.22</version>
            </dependency>
            <dependency>
                <groupId>com.loserico</groupId>
                <artifactId>commons-lang</artifactId>
                <version>${loser.version}</version>
            </dependency>
            <dependency>
                <groupId>com.loserico</groupId>
                <artifactId>commons-spring</artifactId>
                <version>${loser.version}</version>
            </dependency>
            <dependency>
                <groupId>com.loserico</groupId>
                <artifactId>loser-cache</artifactId>
                <version>${loser.version}</version>
            </dependency>
            <dependency>
                <groupId>com.loserico</groupId>
                <artifactId>loser-json</artifactId>
                <version>${loser.version}</version>
            </dependency>
            <dependency>
                <groupId>com.loserico</groupId>
                <artifactId>loser-codec</artifactId>
                <version>${loser.version}</version>
            </dependency>
            <dependency>
                <groupId>com.loserico</groupId>
                <artifactId>loser-web</artifactId>
                <version>${loser.version}</version>
            </dependency>
            <dependency>
                <groupId>com.loserico</groupId>
                <artifactId>loser-validation</artifactId>
                <version>${loser.version}</version>
            </dependency>
            <dependency>
                <groupId>com.loserico</groupId>
                <artifactId>loser-networking</artifactId>
                <version>${loser.version}</version>
            </dependency>
            <dependency>
                <groupId>com.loserico</groupId>
                <artifactId>loser-security</artifactId>
                <version>${loser.version}</version>
            </dependency>
            <dependency>
                <groupId>com.loserico</groupId>
                <artifactId>loser-token-parser</artifactId>
                <version>${loser.version}</version>
            </dependency>
            <dependency>
                <groupId>com.loserico</groupId>
                <artifactId>loser-mybatis</artifactId>
                <version>${loser.version}</version>
            </dependency>
            <dependency>
                <groupId>com.loserico</groupId>
                <artifactId>loser-search</artifactId>
                <version>${loser.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-api</artifactId>
                <version>0.10.8</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>0.10.8</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId>
                <version>0.10.8</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.22</version>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <version>5.0.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>2.0.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.0</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.2.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
